### ISSUE TITLE
Docs feedback on updating-apps

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/replicated-docs#851] opened 2022-12-21 20:19 UTC
This page is missing instructions or a screenshot on configuring the update interval https://docs.replicated.com/enterprise/updating-apps#update-an-application-in-the-admin-console

<img width="538" alt="Screen Shot 2022-12-21 at 2 19 41 PM" src="https://user-images.githubusercontent.com/3730605/208995780-f38ac616-495f-4efd-95b3-c2b890d1843f.png">

**Comment by dexhorthy** [comment] 2022-12-21 20:20
Some more things to showcase:

![Uploading Screen Shot 2022-12-21 at 2.19.59 PM.png…]()

**Comment by paigecalvert** [comment] 2022-12-22 00:51
Thanks @dexhorthy -- Step 2 in this procedure (https://docs.replicated.com/enterprise/updating-apps#configure-automatic-updates) looks like it describes customizing the interval, though there could probably be more detail about the cron expression formatting. I could also see adding more details about all the options in each of the drop downs

Added this story to triage: https://app.shortcut.com/replicated/story/65034/missing-details-in-steps-for-configuring-the-update-interval

**Comment by paigecalvert** [comment] 2023-01-03 20:35
@dexhorthy, @jonquil2002 and I are triaging in our planning today and it looks like this issue might be a duplicate of https://github.com/replicatedhq/replicated-docs/issues/846. Do you agree or were there distinct requests?

**Comment by dexhorthy** [comment] 2023-01-04 22:58
oh weird. Yeah @paigecalvert those look like dupes

**Comment by paigecalvert** [comment] 2023-01-05 18:50
Sounds good, I'll close this one and make sure the details are reflected in the other one :)

**Closed by paigecalvert** 2023-01-05 18:50 UTC
